name: Deploy React App
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12.x"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Packages
        run: npm install

      - name: Configure Git User
        run: |
          git config --global user.email "alexandragalarzag@gmail.com"
          git config --global user.name "MAlexGG"

      - name: Deploy the App
        run: npm run deploy
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}